# permissions for end users to view apipubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apipub-viewer-role
rules:
- apiGroups:
  - publish.example.com
  resources:
  - apipubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - publish.example.com
  resources:
  - apipubs/status
  verbs:
  - get
