
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - publish.example.com
  resources:
  - apipubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - publish.example.com
  resources:
  - apipubs/status
  verbs:
  - get
  - patch
  - update
